
services:
  app1:
    image: api-vehiculos
    ports:
      - "3001:5264"  # Solo para acceso directo (opcional)
    networks:
      - app_network

  app2:
    image: api-vehiculos
    ports:
      - "3002:5264"  # Solo para acceso directo (opcional)
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Nginx escucha en el puerto 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Monta tu configuración
    depends_on:
      - app1
      - app2
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
